#!/bin/bash
DJANGODIR=/webapps/pdf/Fastash
APPDIR=/webapps/pdf
GITRES=https://github.com/AshWorkshop/Fastash.git   #git仓库
APPNAME=pdf
USER=pdf
RMSETTING=$DJANGODIR/config/settings.py    #django的setting地址
NEWSETTING=$DJANGODIR/config/settings.py          #django的setting地址

sudo apt update
sudo apt upgrade
sudo apt install emacs
pip install --upgrade pip
sudo apt install postgresql postgresql-contrib
sudo apt install libpq-dev python-dev
sudo apt install python-dev
sudo apt install supervisor
sudo apt install nginx
pip install virtualenv -i https://pypi.tuna.tsinghua.edu.cn/simple/   #安装函数库

sudo groupadd --system webapps
sudo useradd --system --gid webapps --shell /bin/bash --home $APPDIR $USER   #创建用户

sudo mkdir -p $APPDIR
sudo chown $USER $APPDIR   #授权

sudo apt install git
cd $APPDIR
git clone $GITRES
cd $DJANGODIR
echo "" >> requirements.txt
echo "psycopg2" >> requirements.txt
echo "gunicorn" >> requirements.txt
cd /test/

rm $RMSETTING
cp base.py $NEWSETTING

sudo chown -R $USER:users $APPDIR
sudo chmod -R g+w $APPDIR

sudo su - $USER   #创建虚拟环境并安装依赖

cp gunicorn_start $APPDIR/venv/bin/gunicorn_start
sudo chmod u+x $APPDIR/venv/bin/gunicorn_start
sudo chown $USER $APPDIR/venv/bin/gunicorn_start

cp base_supervisor.conf /etc/supervisor/conf.d/$APPNAME.conf

mkdir -p $APPDIR/logs/
touch $APPDIR/logs/gunicorn_supervisor.log
sudo supervisorctl reread
sudo supervisorctl update

sudo service nginx start
cp base_nginx /etc/nginx/sites-available/$APPNAME
sudo ln -s /etc/nginx/sites-available/$APPNAME /etc/nginx/sites-enabled/$APPNAME
sudo service nginx restart
