#!/bin/bash

DIRNAME=Setting-Pdf
APPNAME=pdf1
SERVICE=example.com

USER=$APPNAME
DJANGODIR=/webapps/$APPNAME/Fastash
APPDIR=/webapps/$APPNAME
RMSETTING=$DJANGODIR/config/settings.py    #django的setting地址
NEWSETTING=$DJANGODIR/config/settings.py          #django的setting地址
GITRES=   #git仓库

cd /$DIRNAME
sed -i 's/pdf1/'$APPNAME'/g' base_supervisor.conf
sed -i 's/pdf1/'$APPNAME'/g' gunicorn_start
sed -i 's/pdf1/'$APPNAME'/g' base_nginx
sed -i 's/pdf1/'$APPNAME'/g' bashForVirtualenv
sed -i 's/example.com/'$SERVICE'/g' base.py
sed -i 's/example.com/'$SERVICE'/g' base_nginx

sudo apt update
sudo apt upgrade
pip install --upgrade pip
sudo apt install libpq-dev python-dev
sudo apt install python-dev
sudo apt install supervisor
sudo apt install nginx
pip install virtualenv -i https://pypi.tuna.tsinghua.edu.cn/simple/   #安装函数库

sudo groupadd --system webapps
sudo useradd --system --gid webapps --shell /bin/bash --home $APPDIR $USER   #创建用户

sudo mkdir -p $APPDIR
sudo chown $USER $APPDIR   #授权

cd $DIRNAME
cp -r Fastash $APPDIR
cd $DJANGODIR
echo "" >> requirements.txt
echo "gunicorn" >> requirements.txt
cd $DIRNAME

rm $RMSETTING
cp base.py $NEWSETTING

sudo chown -R $USER:users $APPDIR
sudo chmod -R g+w $APPDIR

su $USER -s /bin/bash bashForVirtualenv   #创建虚拟环境并安装依赖

cp gunicorn_start $APPDIR/venv/bin/gunicorn_start
sudo chmod u+x $APPDIR/venv/bin/gunicorn_start
sudo chown $USER $APPDIR/venv/bin/gunicorn_start

cp base_supervisor.conf /etc/supervisor/conf.d/$APPNAME.conf    #配置supervisor

mkdir -p $APPDIR/logs/
touch $APPDIR/logs/gunicorn_supervisor.log
sudo supervisorctl reread
sudo supervisorctl update

sudo service nginx start
cp base_nginx /etc/nginx/sites-available/$APPNAME
sudo ln -s /etc/nginx/sites-available/$APPNAME /etc/nginx/sites-enabled/$APPNAME    #配置nginx
sudo service nginx restart

supervisorctl restart $APPNAME
