#!/bin/bash

DIRNAME=/Setting-robotdb
APPNAME=robotdb1
SERVICE=0.0.0.0

cd $DIRNAME
sed -i 's/robotdb/'$APPNAME'/g' base_supervisor.conf
sed -i 's/robotdb/'$APPNAME'/g' gunicorn_start
sed -i 's/robotdb/'$APPNAME'/g' base_nginx
sed -i 's/robotdb/'$APPNAME'/g' bashForVirtualenv
sed -i 's/example.com/'$SERVICE'/g' base.py
sed -i 's/example.com/'$SERVICE'/g' base_nginx
sed -i 's/robotdb/'$APPNAME'/g' applySQl

USER=$APPNAME
DJANGODIR=/webapps/$APPNAME/robot_backend
APPDIR=/webapps/$APPNAME
GITRES=https://gitlab.com/AshWorkshop/robot_backend.git   #git仓库

RMSETTING=$DJANGODIR/config/settings/base.py    #django的setting地址
SETTINGDIR=$DJANGODIR/config/settings/          #django的setting地址

sudo apt update
sudo apt upgrade
sudo apt install emacs
pip install --upgrade pip
sudo apt install libpq-dev python-dev
sudo apt install python-dev
sudo apt install supervisor
sudo apt install nginx
pip install virtualenv -i https://pypi.tuna.tsinghua.edu.cn/simple/   #安装函数库

cd $DIRNAME
sudo aptitude install postgresql postgresql-contrib
su postgres -s /bin/bash applySQl       #申请数据库

sudo groupadd --system webapps
sudo useradd --system --gid webapps --shell /bin/bash --home $APPDIR $USER   #创建用户

sudo mkdir -p $APPDIR
sudo chown $USER $APPDIR   #授权

sudo apt install git
cd $APPDIR
git clone $GITRES
cd $DJANGODIR
echo "" >> requirements.txt
echo "psycopg2" >> requirements.txt
echo "gunicorn" >> requirements.txt
cd $DIRNAME

rm $RMSETTING
cp base.py $SETTINGDIR

sudo chown -R $USER:users $APPDIR
sudo chmod -R g+w $APPDIR

su $USER -s /bin/bash bashForVirtualenv #创建虚拟环境并安装依赖

cp gunicorn_start $APPDIR/venv/bin/gunicorn_start
sudo chmod u+x $APPDIR/venv/bin/gunicorn_start
sudo chown robotdb $APPDIR/venv/bin/gunicorn_start

cp robotdb.conf /etc/supervisor/conf.d/$APPNAME.conf

mkdir -p $APPDIR/logs/
touch $APPDIR/logs/gunicorn_supervisor.log
sudo supervisorctl reread
sudo supervisorctl update

sudo service nginx start
cp robotdb /etc/nginx/sites-available/$APPNAME
sudo ln -s /etc/nginx/sites-available/$APPNAME /etc/nginx/sites-enabled/$APPNAME
sudo service nginx restart
